pip3 install accelerate
pip3 install diffusers
pip3 install einops
pip3 install omegaconf
pip3 install protobuf
pip3 install pytorch-lightning
pip3 install safetensors
pip3 install scipy
pip3 install tokenizers==0.13.3
pip3 install transformers
pip3 install langchain
pip3 install faiss-cpu
pip3 install sentence-transformers
pip3 install pypdf
pip3 install python-dotenv
pip3 install bitsandbytes
pip3 install bs4
pip3 install compel
pip3 install sentence_transformers
pip3 install gradio
pip3 install torch
pip3 install torchvision
pip3 install torchaudio
pip3 install unstructured
pip3 install fastapi
pip3 install fastapi_utils
pip3 install uvicorn[standard]
pip3 install sse_starlette
pip3 install streamlit
pip3 install spacy
pip3 install pandasql
pip3 install llama-cpp-python
